### PR TITLE
454 element measure precision

### PR DESCRIPTION
**Pull request by precicely**

### CODE REVIEW

**Comment by waltsims** [comment]
It looks like I missed something in my original review. I hope you don't mind that I have merged master into your PR to address conflicts.

**Comment by waltsims** [comment]
Also, in `check_element_equality`, there is a typo. I missed it in my first review. The argument should be `actual_element` not `actual_elelment`. Perhaps something like this would be more readable and efficient as well?

```Python
def check_element_equality(
    actual_element: Element,
    expected_element: Element,
) -> bool:
    for field in dataclasses.fields(expected_element):
        expected = getattr(expected_element, field.name)
        actual = getattr(actual_element, field.name)
        if isinstance(expected, np.ndarray):
            if not np.allclose(actual, expected):
                return False
        elif actual != expected:
            return False
    return True
```

**Comment by precicely** [comment]
Hi @waltsims, no problem. Will implement as you suggest.

**Comment by precicely** [comment]
Have now made those changes. That said, and I don't think this is the pull request to do it but perhaps a more elegant solution is to make the `__eq__` method of the `Element` class *just* work? For example, it would be much nicer to write:
```
element_1 == element_2
```
As opposed to the `check_element_equality` function.

I'm guessing the problem right now is the equality of the numpy arrays... I'm happy to take this on if you think it's worthwhile?

**Comment by precicely** [comment]
Something like this:
https://stackoverflow.com/questions/51743827/how-to-compare-equality-of-dataclasses-holding-numpy-ndarray-boola-b-raises

**Comment by waltsims** [comment]
That would be a great addition!

**Comment by waltsims** [comment]
As you said please create a separate PR those changes. Looking forward to it.

**Comment by precicely** [comment]
Will do. Got wrapped up in other things yesterday.

**Review by waltsims — APPROVED** [review]

**Pull request merged**
