### PR TITLE
Add MacOS support

### LINKED ISSUE #69: Support Darwin.
https://stackoverflow.com/a/58930304 Allow for so specific downloads

### PR DESCRIPTION
**Pull request by waltsims**
This PR adds support for M1 Apple processors to k-wave-python. This support only extends to shared memory parallel computations (OMP). CUDA execution is not supported on Apple M1.

This PR does not graciously tell the user that CUDA is not supported and instead throws a file not found when a GPU-accelerated simulation is attempted.

closes #69

### CODE REVIEW

**Comment by waltsims** [comment]
Fixed the tests @faridyagubbayli

**Comment by waltsims** [comment]
Fixed the tests @faridyagubbayli

**Comment by waltsims** [comment]
It looks like with the new test of the simulation_checks, we caught a failure case on this branch.

- [ ] Pass CI

**Review by faridyagubbayli — APPROVED** [review]
So happy to see us testing in MacOS too!

**Pull request merged**
