### PR TITLE
Bump k-Wave test version to v1.4.0

### PR DESCRIPTION
**Pull request by waltsims**
Add new reference to ucl-bug/k-wave with v1.4.0

### CODE REVIEW

**Comment by waltsims** [comment]
TODO:
Update tests and add new examples to cover following updates:
```markdown

source and sensor geometries can now be defined without staircasing artifacts using the kWaveArray class
fwhm can now return the position of the leading and trailing edges
focusedBowlONeil can now return the complex pressure on axis
overlayPlot now allows setting the transparency

Bug Fixes:

    bug fix in using C++ functionality with MATLAB 2020a and later (error with default text encoding)
    bug fix in expandMatrix when using logical matrix as input (gave error)
    bug fix in attenComp (upper part of time variant filter not correctly zeroed).

New Functions:

    computeLinearTransform
    focusedAnnulusONeil
    getAffineMatrix
    getDeltaBLI
    kWaveArray
    makeCartArc
    makeCartBowl
    makeCartDisc
    makeCartRect
    makeCartSphericalSegment
    offGridPoints
    trimZeros
    trimCartPoints

New Examples:

    Example: Defining A Source Using An Array Transducer
    Example: Defining A Sensor Using An Array Transducer
    Example: Modelling Plane Piston And Focused Bowl Transducers
    Example: Modelling A Linear Array Transducer
```

**Comment by waltsims** [comment]
I propose the added functionality of v.1.4.0 be added in separate PRs and that this PR only bump the version of the code we test against.

**Comment by faridyagubbayli** [comment]
> I propose the added functionality of v.1.4.0 be added in separate PRs and that this PR only bump the version of the code we test against.

Makes sense, agreed!

**Review by faridyagubbayli — APPROVED** [review]
LGTM

**Pull request merged**
