### PR TITLE
add_custom_element function in kwave_array

### PR DESCRIPTION
**Pull request by bvale1**
I haven't run the tests since I'm missing a MATLAB function 'FocusBowlONeil' (probably others too) used by the data collectors, I'm not sure where they originate from.

### CODE REVIEW

**Comment by waltsims** [comment]
Thanks for the PR.

the version of k-Wave we test against is v1.3.0 which can be found [here](https://github.com/ucl-bug/k-wave). It has for example [FocusBowlONeil](https://github.com/ucl-bug/k-wave/blob/main/k-Wave/focusedBowlONeil.m) and others you might be missing. Hope this helps!

**Comment by waltsims** [comment]
It looks like you're currently missing your data collector in Matlab in this PR.

**Comment by bvale1** [comment]
You're right, although I installed k-wave Matlab did not add it to the search path automatically, my dev environment should be set up correctly now

**Comment by waltsims** [comment]
Did you mean to close this?

**Comment by waltsims** [comment]
> You're right, although I installed k-wave Matlab did not add it to the search path automatically, my dev environment should be set up correctly now

I'll update the readme to make this easier in the future.

**Pull request closed without merging**
