### PR TITLE
support darwin cpu execution.

### LINKED ISSUE #69: Support Darwin.
https://stackoverflow.com/a/58930304 Allow for so specific downloads

### PR DESCRIPTION
**Pull request by waltsims**
This PR adds darwin cpu execution of k-wave simulations and depends on darwin compilation of the binaries which will be published to github shortly.

closes #69

### CODE REVIEW

**Comment by waltsims** [comment]
This PR depends on the publishing of the binaries and ability to download them upon install.

**Review by faridyagubbayli — APPROVED** [review]
LGTM! Thank you for adding this feature. Will be great to finally run the examples on Mac :)

**Comment by waltsims** [comment]
compilation is currently working but without openmp which makes it unbearably slow. Need to work on static compilation with openmp before merging this.

**Comment by waltsims** [comment]
Replaced with #410

**Pull request closed without merging**
