### PR TITLE
Update pytest.yml

### PR DESCRIPTION
**Pull request by waltsims**

### CODE REVIEW

**Comment by waltsims** [comment]
@faridyagubbayli I was working on a review and thought I would try some things myself. If you like this merge it in.

**Comment by faridyagubbayli** [comment]
@waltsims I started with the same solution ([see this commit](https://github.com/waltsims/k-wave-python/pull/260/commits/34e0ced95f2cb684daa36587c89ef29fffaa96e8)) as yours. However, I [read this article](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and thought `outputs` field is deprecated. I even remember seeing deprecation warning in the logs but I can't find it. The article seems to talk about a different mechanism. Anyway, I do not have an evidence that this field is deprecated. Going to merge your changes, thanks for looking deeper!

**Review by faridyagubbayli — APPROVED** [review]
LGTM!

**Comment by waltsims** [comment]
> @waltsims I started with the same solution ([see this commit](https://github.com/waltsims/k-wave-python/pull/260/commits/34e0ced95f2cb684daa36587c89ef29fffaa96e8)) as yours. However, I [read this article](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and thought `outputs` field is deprecated. I even remember seeing deprecation warning in the logs but I can't find it. The article seems to talk about a different mechanism. Anyway, I do not have an evidence that this field is deprecated. Going to merge your changes, thanks for looking deeper!

Yeah not sure about deprivation... this is great to have in main. Thanks for doing this. It was a nice surprise!

**Pull request merged**
