### PR TITLE
Separate DLL checking in windows

### LINKED ISSUE #419: [BUG] Windows re-downloads binaries on every import (and double-downloads DLLs)
**Describe the bug**
Every time `kwave` is imported on windows, `__init__.py` detects that the metadata URL for the `.dll` files does not match, and proceeds to re-download all of the binaries, slowing import to 30s+.

The problem is in `__init__/binaries_present`, which loops through `omp` and `cuda` architectures. There aren't separate `omp` and `cuda` DLLs, but they get indexed in both `URL_DICT['windows']['omp']` and `URL_DICT['windows']['windows']`. When checking to see if they are present, `binaries_present` attaches the `binary_type` to `binary_list` when assembling the list, which triggers `_is_binary_present` to check for the DLL's existence, its hash to match the recorded metadata, _and it's URL to be present in `latest_urls`.  But because the URLS are only checked for the current architecture, it winds up doing this (when it gets to each DLL):

1. Check for the OMP URL to match. It won't, so it flags for redownload
2. Check for the CUDA URL to match. It will, but we'll already be flagged.
3. Download the .dll from the OMP URL
4. Save the metadata with the OMP URL
5. Download the .dll from the CUDA URL (same file as OMP), overwriting the same file.
6. Overwrite the metadata with the CUDA URL, ensuring that the URL check will fail on step 1 next time.

This has a secondary problem of double-downloading every windows DLL, even though they are both the same file.

**To Reproduce**
On windows:
`import kwave`

**Expected behavior**
We should separately list the DLLs from the .exes, so that they only get checked and downloaded once.

**Desktop (please complete the following information):**
 - Windows 10

### PR DESCRIPTION
**Pull request by peterhollender**
Changes the way windows checks for DLLs to prevent re-downloading on every import and double-downloading of DLLs. 

Closes #419

### CODE REVIEW

**Comment by peterhollender** [comment]
How would you like a windows-specific platform test to be implemented? I see the Codecov report flagged the `if PLATFORM == "windows"` condition.

**Comment by waltsims** [comment]
Hey @peterhollender,

I added a failing test to cover the double download case.

I believe the following patch is all we need to fix this issue.

```python
def get_windows_release_urls(architecture: str) -> list:
    specific_filenames = [EXECUTABLE_PREFIX + architecture + ".exe"]
    if architecture == "omp":
        specific_filenames += WINDOWS_DLLS
    release_urls = [PREFIX.format(architecture.upper(), PLATFORM.lower()) + filename for filename in specific_filenames]
    return release_urls
```

Could you confirm that using only this patch works for you?


Walter

**Comment by waltsims** [comment]
I think codecov's is having an issue tonight. I hope you don't mind that I pushed to your fork.

**Review by waltsims — CHANGES_REQUESTED** [review]
please see my comments.

**Comment by peterhollender** [comment]
> Hey @peterhollender,
> 
> I added a failing test to cover the double download case.
> 
> I think we can simplify the PR before merging it in. I believe the following patch is all we need to fix this issue.
> 
> ```python
> def get_windows_release_urls(architecture: str) -> list:
>     specific_filenames = [EXECUTABLE_PREFIX + architecture + ".exe"]
>     if architecture == "omp":
>         specific_filenames += WINDOWS_DLLS
>     release_urls = [PREFIX.format(architecture.upper(), PLATFORM.lower()) + filename for filename in specific_filenames]
>     return release_urls
> ```
> 
> Could you confirm that using only this patch (along with the updated import statement) works for you?
> 
> Walter

Yeah, that simpler patch works. I started with something like that and then made it more complicated (I think I was trying to better organize it in case we ever wanted to install _just_ the OMP or _just_ the CUDA binaries, but I didn't carry that notion all the way through. If we were going separate them out, you'd probably want to create a whole new `kspaceFirstOrder-DLL-windows` repo to hold them. 

One thing to note about this patch is that by setting the URL of the DLLs to the OMP version, everyone who has it installed is going to trigger one more re-install the next time they import, since they will all have double-installed the CUDA version over the OMP version and left the CUDA URL in their metadata.

**Comment by waltsims** [comment]
Yeah in the future it would be great to clean up the binary releases and repositories. Good point on that last update. If you'd prefer setting the DLL repo to CUDA that's fine by me.

**Review by waltsims — APPROVED** [review]

**Pull request merged**
